apiVersion: apps/v1
kind: Deployment
metadata:
  name: test-logger
  labels:
    app: test-logger
spec:
  replicas: 1
  selector:
    matchLabels:
      app: test-logger
  template:
    metadata:
      labels:
        app: test-logger
    spec:
      containers:
        - name: test-logger
          image: registry.storesync.io/config:1.0-SNAPSHOT
          ports:
            - containerPort: 8080
          imagePullPolicy: Always
          env:
            - name: JVM_HEAP_SIZE
              value: 200m
          volumeMounts:
            - mountPath: /mnt/log
              name: log
          resources:
            requests:
              memory: "300m"
              cpu: "100m"
      volumes:
        - name: log
          hostPath:
            path: /mnt/log
      imagePullSecrets:
        - name: regcred
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 25%
      maxSurge: 25%
---
apiVersion: v1
kind: Service
metadata:
  name: test-logger
spec:
  selector:
    app: test-logger
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080



eyJhbGciOiJSUzI1NiIsImtpZCI6IndyVnF1eDdKYnJSZkxVOHZXSXJjcWdkdWhDMUdyT2Z6MHFmQ01rSXVfQWsifQ: eyJpc3MiOiJrdWJlcm5ldGVzL3NlcnZpY2VhY2NvdW50Iiwia3ViZXJuZXRlcy5pby9zZXJ2aWNlYWNjb3VudC9uYW1lc3BhY2UiOiJrdWJlcm5ldGVzLWRhc2hib2FyZCIsImt1YmVybmV0ZXMuaW8vc2VydmljZWFjY291bnQvc2VjcmV0Lm5hbWUiOiJrdWJlcm5ldGVzLWRhc2hib2FyZC10b2tlbi1zcHpzeiIsImt1YmVybmV0ZXMuaW8vc2VydmljZWFjY291bnQvc2VydmljZS1hY2NvdW50Lm5hbWUiOiJrdWJlcm5ldGVzLWRhc2hib2FyZCIsImt1YmVybmV0ZXMuaW8vc2VydmljZWFjY291bnQvc2VydmljZS1hY2NvdW50LnVpZCI6ImJmNjY2MTk5LWMzMjQtNDRiNi1hZjVhLWI4YjllYWQ3M2E2ZCIsInN1YiI6InN5c3RlbTpzZXJ2aWNlYWNjb3VudDprdWJlcm5ldGVzLWRhc2hib2FyZDprdWJlcm5ldGVzLWRhc2hib2FyZCJ9: sQoR8D6epuHaSxmpAhOdRSxG3TMVFZJFdPOAeexZsI4x27jf0JrClKUAvQ3PWRBfpKb8LwXCC4V9QXGubDWrufOqVWpRz6bPuRJE4jAFUg3jjfQPxPY8-VXwFD7bfJfQDuymHVj0RiOPqEG3uqaGtT_NTaHs1FW6iri8mNx8pFlAkUvRfst5G_VGN_3rY-4kTwFj3QIFSIOVC88L20ZrnOZlXkAl9pbh7XUSHp5tC4RV_hyPPLdoB4jjDpWXYP2jJ8K-K0naCSO0qOfeXNHGJpi1wPjm_-vEaRw0tywZunrI8l3koangx2WZmetpTRYBWNy3xuE63Ccdllh7GGEl7g: