apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: data-elk-elasticsearch-master-0
  labels:
    app: elasticsearch
    release: elk
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 3Gi
  storageClassName: "my-local-storage"

---

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: data-elk-logstash-0
  labels:
    app: elasticsearch
    release: elk
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 3Gi
  storageClassName: "my-local-storage"

---

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: data-elk-elasticsearch-data-0
  labels:
    app: elasticsearch
    release: elk
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 3Gi
  storageClassName: "my-local-storage"
